backend:
  name: github
  repo: codelastnight/artmachine
  branch: main

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  
  - name: artists
    label: Artists
    folder: content/artists
    create: true
    fields:
      - { name: path, label: Path }
      - { name: artistName, label: Artist Name }
      - { name: about, label: About, widget: text }
      - { name: shop, label: Shop }

      - label: "Social Links"
        name: "links"
        widget: "list"
        summary: '{{fields.link}}'
        field: {label: Link, name: link, widget: string}

